// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuinielaFIFA2026.Web.Data;

#nullable disable

namespace QuinielaFIFA2026.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527132305_AddUserComplement")]
    partial class AddUserComplement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Lote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowDraw")
                        .HasColumnType("boolean");

                    b.Property<string>("AwayFlagEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwaySlot")
                        .HasColumnType("text");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .HasColumnType("text");

                    b.Property<string>("HomeFlagEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeSlot")
                        .HasColumnType("text");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MatchDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatchNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.MatchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchResults");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LoteId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.PrediccionClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EquipoElegido")
                        .HasColumnType("text");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanillaId");

                    b.ToTable("PrediccionesClasificacion");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanillaId")
                        .HasColumnType("integer");

                    b.Property<string>("PredictedResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlanillaId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.MatchResult", b =>
                {
                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.Match", "Match")
                        .WithOne("Result")
                        .HasForeignKey("QuinielaFIFA2026.Web.Data.Models.MatchResult", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Planilla", b =>
                {
                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.Lote", "Lote")
                        .WithMany("Planillas")
                        .HasForeignKey("LoteId");

                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.User", "User")
                        .WithMany("Planillas")
                        .HasForeignKey("UserId");

                    b.Navigation("Lote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.PrediccionClasificacion", b =>
                {
                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.Planilla", "Planilla")
                        .WithMany("PrediccionesClasificacion")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Prediction", b =>
                {
                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.Match", "Match")
                        .WithMany("Predictions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuinielaFIFA2026.Web.Data.Models.Planilla", "Planilla")
                        .WithMany("Predictions")
                        .HasForeignKey("PlanillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Lote", b =>
                {
                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Match", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.Planilla", b =>
                {
                    b.Navigation("PrediccionesClasificacion");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("QuinielaFIFA2026.Web.Data.Models.User", b =>
                {
                    b.Navigation("Planillas");
                });
#pragma warning restore 612, 618
        }
    }
}
